# Generated by Django 5.2 on 2025-05-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefas',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tarefas',
            old_name='update',
            new_name='updated_at',
        ),
    ]
